image: gitlab_local_maven:3.6.0-jdk-8

stages:
  - build
  - test
  - package
  - deploy

cache:
  key: maven-repository-cache
  paths:
    - .m2/repository
    - target
variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  tags:
    - Backend
  stage: build
  script:
    - mvn compile

test:
  tags:
    - Backend
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

package:
  tags:
    - Backend
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package -Dmaven.test.skip=true
  artifacts:
    paths:
      - jpa-converter-generator-annotations/target/jpa-converter-generator-annotations-1.0-SNAPSHOT.jar
      - jpa-converter-generator-processors/target/jpa-converter-generator-processors-1.0-SNAPSHOT.jar
  only:
    - master@MZH-Backend/jpa-converter-generator

deploy:
  tags:
    - Backend
  stage: deploy
  when: manual
  script:
    - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true
  only:
    - master@MZH-Backend/jpa-converter-generator
